### ISSUE TITLE
Kit App Template vs. Kit SDK

### ISSUE THREAD

**Issue by cadop** [NVIDIA-Omniverse/kit-app-template#13]
What is the difference with this template and manually building vs using the kit SDK that is now part of the omniverse download link?

They seem to be the exact same thing. When would one be used over the other?

**Comment by SchultzC** [comment]
Thank you for your  questions.


**The kit-app-template repository:** This offers a streamlined integration with developer tooling and templates, helping developers manage and own the applications they build. It includes convenient tooling for creating new apps and extensions based on templates, simplified app launch, developer extensions (for troubleshooting and debugging), and more.

**Building manually:** This approach remains possible but requires a deeper knowledge of developing Kit applications since the convenience features of the tooling and templates are not present.

**The direct download link:** This provides a preconfigured version of the Kit Base Editor (also available as a template within this repository). While it can be used as a starting point for development, it comes with some of the same trade-offs as the manual build approach. It is recommended to leverage this as an initial preview of the types of things that can be built with the Kit SDK.

**Recommendation:** For app and extension development, it is generally recommended to use the kit-app-template repository as the starting point.

**Comment by cadop** [comment]
Would you be able to add some context for the pro/con of each one? e.g. you mention `but requires a deeper knowledge of developing Kit applications`, is there a benefit to using this if you _do_ have a deeper knowledge?

It would be helpful to understand the relationship between all of them, you mentioned `it comes with some of the same trade-offs as the manual build approach`, but i'm not sure what those trade-offs are.

**Comment by SchultzC** [comment]
Sure, here are is a bit more information on each:

### Without Kit App Template Options:

#### 1. Direct Download:
This should primarily be considered a preview of what you can build with Kit. It is provided for demonstration purposes and is not the recommended development path. However, with the correct background knowledge, it **could** be used.

#### 2. Building Manually:
Manually building a Kit app and its associated extensions is indeed possible but requires:
- In-depth knowledge of the layout and structure of configuration files.
- Familiarity with the directory structure for Apps/Extensions.
- Understanding of build configuration and associated files.

### With Kit App Template:

#### **Pros:**
- **Integrated Tooling:** Facilitates setting up required boilerplate via command-line tools. This is executed through `./repo.sh template new`, applicable to both Apps and Extensions.
- **Build, Test, and Package Tools:** Updated tooling workflows (`./repo.sh build`, `./repo.sh test`, `./repo.sh package`, etc.) ensured to work over the provided structure.
- **Convenience Tooling:** For example, simplified application launch with `./repo.sh launch`, and the ability to attach developer extensions directly. The manual approach would be : `./_build/{platform}/{config}/kit/kit  _build/{platform}/{config}/apps/{app_name}.kit --enable omni.kit.developer.bundle`. 
- **Ongoing Support:** Regular updates and continued support for best practices and new features as Kit and the Omniverse developer platform evolve.

#### **Cons:**
- **Initial Migration Effort:** Migrating a long-standing legacy Kit application (pre-Kit 106) with numerous external dependencies might incur a significant initial effort and cost.

### Conclusion:
For most developers, especially those newer to Kit development or those working on newer projects, leveraging the Kit App Template is highly recommended due to its streamlined workflow and support. Experienced developers with existing legacy Kit applications may prefer to continue with the manual approach if updating is too resource-intensive.

**Comment by cadop** [comment]
Thank you for the detailed explanation. I have a few more questions to clarify the differences and potential use cases:

1. **Specific Scenarios**: Could you provide specific examples or scenarios where using the Kit App Template would be advantageous over manually building an app, and vice versa? This would help in understanding practical applications of each approach.

2. **In-Depth Knowledge Benefits**: You mentioned that manually building requires in-depth knowledge but didn't specify the benefits of using this approach if one possesses such knowledge. Are there performance benefits, customization options, or other advantages that come with the manual approach?

3. **Trade-Offs**: You indicated that the direct download comes with trade-offs similar to the manual build approach. Could you list and explain these trade-offs in more detail?

4. **Legacy Applications**: For developers with legacy Kit applications, what are the key considerations they should evaluate when deciding whether to migrate to the Kit App Template or stick with their current setup?

Your insights on these points would be very helpful in making an informed decision. Thank you!

**Comment by SchultzC** [comment]
1. **Specific Scenarios:**
   - **Direct Download:** Use this for a quick preview of what’s possible with the Kit SDK or for viewing and minor edits of USD content. It’s not well suited for full-scale development due to the lack of integrated tooling.
   - **Manual Build:** If you have an existing, heavily customized Kit application with your own maintenance/build tools. Certainly not recommended if starting from scratch
   - **Kit App Template:** Recommended for most developers. It leverages the same Kit Kernel and provides integrated tooling and best-practice templates for a smoother development process.

2. **Benefits of In-Depth Knowledge:**
   - While deeper knowledge can enhance development efficiency, opting for a manual build or customizing the direct download does not yield any additional performance or customization benefits over the Kit App Template.

3. **Trade-Offs:**
   - **Kit App Template vs. Direct Download:** The direct download avoids the need for initial setup and build but lacks in ease of customization and development.
   - **Kit App Template vs. Manual Build:** Manual builds offer flexibility in using your own tools or build system (if you have already have it) but is more challenging to set up and maintain.

4. **Migration Considerations:**
   - Evaluate the Kit App Template repository and [companion tutorial](https://docs.omniverse.nvidia.com/kit/docs/kit-app-template/latest/docs/intro.html). This will help determine if migrating is right for you.  The needs of each development team will vary, evaluation of what is achievable (and easy) with Kit App Template is likely the best approach.

I hope this clarifies things.

**Comment by cadop** [comment]
Thanks, this clarifies alot. 

You mention Kit App Template vs. Manual Build.  What is the manual build you are referring to? The documentation has a section for [building the App](https://github.com/NVIDIA-Omniverse/kit-app-template?tab=readme-ov-file#3-build ). How is that different than "manual build", it seems both would let you customize the toolchain. 

That companion tutorial is really really excellent. Much appreciated.

**Comment by SchultzC** [comment]
Glad you like the companion tutorial.

The section of the documentation you are referencing is leveraging the build tooling that ships with Kit App Template (`repo build`).  This is the best option as that tooling ensures that the right components will be compiled (if needed) and the required build artifacts are placed in the correct location.  And you're right, you can build around this tooling as needed.

When we discuss a "manual build" we are talking about working directly with the Kit Kernel and doing the same operations that `repo build` does either manually or via your own tooling.  While technically possible, it is not a recommended or supported workflow.

**In almost all cases we would suggest:**  Use the tooling provided by Kit App Template and if you see something missing please file a feature request.
