### ISSUE TITLE
Creating extension does not create .vscode config

### ISSUE THREAD

**Issue by apric0ts** [NVIDIA-Omniverse/kit-app-template#15]
When creating extensions via extension manager, it creates a .vscode config file but this doesn't. So VSCode debugger does not work

**Comment by SchultzC** [comment]
Rather than using the extension manager.  The recommended approach for creating a new extension is via `./repo.sh template new` (Linux) or `.\repo.bat template new` (Windows)

The extension template most like the one from the extension manager is this one:

https://github.com/NVIDIA-Omniverse/kit-app-template/tree/main/templates/extensions/python_ui

Instructions exist there for generating the extension and adding to your application via the `.kit` file

**Comment by apric0ts** [comment]
Thanks for getting back to me so quick, apologies for not being clear. I used this template and the command you gave me to generate extensions. The extension generated from this kit-app-template does not build the `.vscode` folder with a `launch.json` file that I'd like to use, so I can debug my code with the [VS Code Debugger Extension](https://docs.omniverse.nvidia.com/extensions/latest/ext_vs-code-link.html#configure-your-project-for-debugging).

Creating extensions with the extension manager however does create this `.vscode` folder, which is why I brought that up.

**Comment by SchultzC** [comment]
I see.  Thank you for clarifying.  That file exists in [`kit-app-template/.vscode`](https://github.com/NVIDIA-Omniverse/kit-app-template/tree/main/.vscode) now.   VS Code should be able to find it under the name "Python: Remote Attach" 

After starting the debug session form VS Code it might be required to hit "refresh" on the VS Code Link extension to attach.
